### ISSUE TITLE
Layering issues

### ISSUE THREAD

**Issue by FoxBotGames** [PriestTheBeast/Compressed-Factory#8]
7 by 7 by 7 should require 2 layers, however refuses to create the factory. 1 layer does not work (as stated max for 1 layer is 5 by 5 by 5)

**Comment by FoxBotGames** [comment]
My thinking is it's running into a math problem.
My theory is that 3x3x3 (smallest size) thru either 5x5x5 or 6x6x6 are Tier 1. (1 layer)
7x7x7 thru 10x10x10 are Tier 2. (2 layers)
11x11x11 thru 15x15x15 are Tier 3. (3 layers)
If you make a double layer 7x7x7, the mod's registering it as too 'small' for a Tier 2.. but a single layer 7x7x7 is too 'big' for a Tier 1.
I've tried a triple layer 11x11x11 and it's got the same issue. Doesn't work. But a 14x14x14 and 15x15x15 triple layer DO work.
I think the tier system for compression built into the mod is causing it to confuse itself.
~Vaygrim (Pack dev and my higher up)

**Comment by PriestTheBeast** [comment]
I will look into it, but pls check the mod description to see the compressor sizes that work and think of it like the cube of air inside.
![image](https://user-images.githubusercontent.com/25922992/34080977-6076d944-e33e-11e7-8018-cdf558db86a7.png)
Like you can see in the image, there is no 7x7x7 compressor, only 6x6x6 and 9x9x9, this is because you can have a 4x4x4 cube of air inside with one layer, that results in a 6x6x6 compressor, and then for the 5x5x5 cube of air inside you need to layers, that result in a 9x9x9 compressor
I will rewrite the mod description when i can, since it is mighty confusing.
But the mod should be working fine, just try to think of the cube of air inside the compressor instead of the compressor size.
