### ISSUE TITLE
Stuck In Factory

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [PriestTheBeast/Compressed-Factory#9]
I built a 15^3 for my first factory, finally got it working (might want to mention that you can't have anything but casing blocks along the outside edges of the frame), and went in.  I promptly fell from I don't know how high to the bottom of my compressed factory space (nearly dying, were it not for extra health and armor from other mods).  I don't know how high up I fell from for two reasons, 1) there was no lighting inside the factory (despite the config lighting option being set to true), and 2) the factory has no top (which, if I'm reading the image from TwistedTV right, it should have).  After much wandering around, I determined that the factory also lacked an exit teleporter.  I had to kill myself in order to escape!

I'm pretty sure this is NOT how this mod is supposed to work, so what's going on?!?  I'm running Minecraft 1.12.2 and Compressed Factories 1.2.4.

**Comment by PriestTheBeast** [comment]
No idea how that happened, it should have teleported you to the room you made, but instead teleported you to the dimension to some weird coordinates.
Without more info i cannot know what happen, or even have a good guess.
If you want a fix then my best advice is to "reset" the mod. This means, update my mod to 1.2.5, change the id of the dimensions in the config and create the factory again.
If it happens again, then pls give me more information like the steps that led to the factory creation, the chat, etc, so that i can try to recreate the bug.
Also, there is a debug command called overworldTp or otp. You can just do /otp and you will be teleported back to your bed/spawn in the overworld.
Thx for the issue and if you have any questions feel free to ask.
